const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const CHECK_TOKEN = 'CHECK_TOKEN';
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
const ADD_PROPOSALS_FAILURE = 'ADD_PROPOSALS_FAILURE';
const ADD_PROPOSALS_SUCCESS = 'ADD_PROPOSALS_SUCCESS';
const GET_PROPOSALS_LIST_FAILURE = 'GET_PROPOSALS_LIST_FAILURE';
const GET_PROPOSALS_LIST_SUCCESS = 'GET_PROPOSALS_LIST_SUCCESS';
const SEND_OFFER_FAILURE = 'SENT_OFFER_FAILURE';
const SEND_OFFER_SUCCESS = 'SENT_OFFER_SUCCESS';
const DELETE_PROPOSAL_SUCCESS = 'DELETE_PROPOSAL_SUCCESS';
const DELETE_PROPOSAL_FAILURE = 'DELETE_PROPOSAL_FAILURE';
const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
const GET_USER_FAILURE = 'GET_USER_FAILURE';
const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
const LOGOUT_USER = 'LOGOUT_USER';
const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
const GET_MY_PROPOSALS_FAILURE = 'GET_MY_PROPOSALS_FAILURE';
const GET_MY_PROPOSALS_SUCCESS = 'GET_MY_PROPOSALS_SUCCESS';
const GET_MY_OFFERS_PROPOSAL_FAILURE = 'GET_MY_OFFERS_PROPOSAL_FAILURE';
const GET_MY_OFFERS_PROPOSAL_SUCCESS = 'GET_MY_OFFERS_PROPOSAL_FAILURE';
const RIFLE_MY_CONTACT_FAILURE = 'RIFLE_MY_CONTACT_FAILURE';
const RIFLE_MY_CONTACT_SUCCESS = 'RIFLE_MY_CONTACT_SUCCESS';

const API = {
  HOST: 'http://localhost:',
  PORT: '8033'
};

API.URL = API.HOST + API.PORT;

export { API, LOGIN_SUCCESS, LOGIN_FAILURE, CHECK_TOKEN, SIGNUP_SUCCESS, SIGNUP_FAILURE,
  ADD_PROPOSALS_FAILURE, ADD_PROPOSALS_SUCCESS, GET_PROPOSALS_LIST_FAILURE,
    GET_PROPOSALS_LIST_SUCCESS, SEND_OFFER_FAILURE, SEND_OFFER_SUCCESS,
      DELETE_PROPOSAL_SUCCESS, DELETE_PROPOSAL_FAILURE, GET_USER_SUCCESS,
        GET_USER_FAILURE, UPLOAD_FILE_SUCCESS, LOGOUT_USER,
          UPDATE_PROFILE_SUCCESS, GET_MY_PROPOSALS_FAILURE, GET_MY_PROPOSALS_SUCCESS,
            GET_MY_OFFERS_PROPOSAL_FAILURE, GET_MY_OFFERS_PROPOSAL_SUCCESS,
              RIFLE_MY_CONTACT_FAILURE, RIFLE_MY_CONTACT_SUCCESS };
